# execute tmux if it's installed, only in interactive shells and if it's not trying to run within itself
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi

alias c="clear"
alias l="ls -lah"
alias cb="xclip -se c" # copy input to clipboard

# Create password-protected 7-zip archive with filenames hidden
compress() {
	7z a -p -mhe "$1" "$1"		
}

# Shred directory recursively and then delete it
shreddir() {
	find "$1" -type f -exec shred -uvz {} \;
	rm -r "$1"
	echo "Deletion finished"
}
